# Generated by Django 2.1.4 on 2019-03-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition',
            new_name='water_object_condition',
        ),
    ]
