# Generated by Django 2.1.4 on 2019-01-14 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observationDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'discharge',
            },
        ),
        migrations.CreateModel(
            name='Hydrologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hydrologists',
            },
        ),
        migrations.CreateModel(
            name='Hydropost',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('nameEn', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'hydroposts',
            },
        ),
        migrations.CreateModel(
            name='HydropostCategory',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hydropost_categories',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observationDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydrologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrology.Hydrologist')),
                ('hydropost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrology.Hydropost')),
            ],
            options={
                'db_table': 'observations',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hydrology.Observation'),
        ),
        migrations.AddField(
            model_name='hydropost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hydrology.HydropostCategory'),
        ),
        migrations.AddField(
            model_name='hydropost',
            name='hydrologists',
            field=models.ManyToManyField(through='hydrology.Observation', to='hydrology.Hydrologist'),
        ),
        migrations.AddField(
            model_name='hydropost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hydrology.Region'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hydrology.Observation'),
        ),
    ]
