# Generated by Django 2.1.4 on 2019-03-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0002_auto_20190312_1135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('observation', 'observation_datetime')},
        ),
    ]
