# Generated by Django 2.1.4 on 2019-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0006_auto_20190315_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='level',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
